src/Entity/Produit.php
<?php

namespace App\Entity;

use App\Model\TimestampedInterface;
use App\Repository\ProduitRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: ProduitRepository::class)]
class Produit implements TimestampedInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $nom = null;

    #[ORM\Column(type: Types::TEXT, nullable: true)]
    private ?string $description = null;

    #[ORM\Column(nullable: true)]
    private ?int $prix_reduit = null;

    #[ORM\Column]
    private ?int $prix = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $marque = null;

    #[ORM\Column(length: 255, nullable: true)]
    private ?string $nom_vendeur = null;

    #[ORM\Column(type: Types::BIGINT, nullable: true)]
    private ?string $contact_vendeur = null;

    #[ORM\Column]
    private ?bool $disponibilite = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    private ?\DateTimeInterface $updatedAt = null;

    #[ORM\ManyToOne(inversedBy: 'produit')]
    #[ORM\JoinColumn(nullable: false)]
    private ?SousCategorie $sousCategorie = null;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Commentaire::class, orphanRemoval: true)]
    private Collection $commentaire;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Image::class, cascade: ["persist"], orphanRemoval: true)]
    private Collection $image;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: CommandeProduit::class, orphanRemoval: true)]
    private Collection $commande_produit;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Panier::class, orphanRemoval: true)]
    private Collection $panier;

    #[ORM\OneToMany(mappedBy: 'produit', targetEntity: Souhait::class, orphanRemoval: true)]
    private Collection $souhait;

    #[ORM\Column(length: 255)]
    private ?string $couverture_img = null;

    public function __construct()
    {
        $this->commentaire = new ArrayCollection();
        $this->image = new ArrayCollection();
        $this->commande_produit = new ArrayCollection();
        $this->panier = new ArrayCollection();
        $this->souhait = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->nom;
    }

    public function setNom(string $nom): self
    {
        $this->nom = $nom;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(?string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getPrixReduit(): ?float
    {
        return $this->prix_reduit;
    }

    public function setPrixReduit(?float $prix_reduit): self
    {
        $this->prix_reduit = $prix_reduit;

        return $this;
    }

    public function getPrix(): ?float
    {
        return $this->prix;
    }

    public function setPrix(float $prix): self
    {
        $this->prix = $prix;

        return $this;
    }

    public function getMarque(): ?string
    {
        return $this->marque;
    }

    public function setMarque(?string $marque): self
    {
        $this->marque = $marque;

        return $this;
    }

    public function getNomVendeur(): ?string
    {
        return $this->nom_vendeur;
    }

    public function setNomVendeur(?string $nom_vendeur): self
    {
        $this->nom_vendeur = $nom_vendeur;

        return $this;
    }

    public function getContactVendeur(): ?string
    {
        return $this->contact_vendeur;
    }

    public function setContactVendeur(?string $contact_vendeur): self
    {
        $this->contact_vendeur = $contact_vendeur;

        return $this;
    }

    public function isDisponibilite(): ?bool
    {
        return $this->disponibilite;
    }

    public function setDisponibilite(bool $disponibilite): self
    {
        $this->disponibilite = $disponibilite;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getUpdatedAt(): ?\DateTimeInterface
    {
        return $this->updatedAt;
    }

    public function setUpdatedAt(?\DateTimeInterface $updatedAt): self
    {
        $this->updatedAt = $updatedAt;

        return $this;
    }

    public function getSousCategorie(): ?SousCategorie
    {
        return $this->sousCategorie;
    }

    public function setSousCategorie(?SousCategorie $sousCategorie): self
    {
        $this->sousCategorie = $sousCategorie;

        return $this;
    }

    /**
     * @return Collection<int, Commentaire>
     */
    public function getCommentaire(): Collection
    {
        return $this->commentaire;
    }

    public function addCommentaire(Commentaire $commentaire): self
    {
        if (!$this->commentaire->contains($commentaire)) {
            $this->commentaire->add($commentaire);
            $commentaire->setProduit($this);
        }

        return $this;
    }

    public function removeCommentaire(Commentaire $commentaire): self
    {
        if ($this->commentaire->removeElement($commentaire)) {
            // set the owning side to null (unless already changed)
            if ($commentaire->getProduit() === $this) {
                $commentaire->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImage(): Collection
    {
        return $this->image;
    }

    public function addImage(Image $image): self
    {
        if (!$this->image->contains($image)) {
            $this->image->add($image);
            $image->setProduit($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->image->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getProduit() === $this) {
                $image->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, CommandeProduit>
     */
    public function getCommandeProduit(): Collection
    {
        return $this->commande_produit;
    }

    public function addCommandeProduit(CommandeProduit $commandeProduit): self
    {
        if (!$this->commande_produit->contains($commandeProduit)) {
            $this->commande_produit->add($commandeProduit);
            $commandeProduit->setProduit($this);
        }

        return $this;
    }

    public function removeCommandeProduit(CommandeProduit $commandeProduit): self
    {
        if ($this->commande_produit->removeElement($commandeProduit)) {
            // set the owning side to null (unless already changed)
            if ($commandeProduit->getProduit() === $this) {
                $commandeProduit->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Panier>
     */
    public function getPanier(): Collection
    {
        return $this->panier;
    }

    public function addPanier(Panier $panier): self
    {
        if (!$this->panier->contains($panier)) {
            $this->panier->add($panier);
            $panier->setProduit($this);
        }

        return $this;
    }

    public function removePanier(Panier $panier): self
    {
        if ($this->panier->removeElement($panier)) {
            // set the owning side to null (unless already changed)
            if ($panier->getProduit() === $this) {
                $panier->setProduit(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Souhait>
     */
    public function getSouhait(): Collection
    {
        return $this->souhait;
    }

    public function addSouhait(Souhait $souhait): self
    {
        if (!$this->souhait->contains($souhait)) {
            $this->souhait->add($souhait);
            $souhait->setProduit($this);
        }

        return $this;
    }

    public function removeSouhait(Souhait $souhait): self
    {
        if ($this->souhait->removeElement($souhait)) {
            // set the owning side to null (unless already changed)
            if ($souhait->getProduit() === $this) {
                $souhait->setProduit(null);
            }
        }

        return $this;
    }

    public function getCouvertureImg(): ?string
    {
        return $this->couverture_img;
    }

    public function setCouvertureImg(string $couverture_img): self
    {
        $this->couverture_img = $couverture_img;

        return $this;
    }
}

src/Controller/CompteController.php
<?php

namespace App\Controller;

use App\Entity\Adresse;
use App\Entity\Commande;
use App\Entity\Panier;
use App\Entity\Produit;
use App\Form\PanierType;
use App\Repository\AdresseRepository;
use App\Repository\CategorieRepository;
use App\Repository\CommandeRepository;
use App\Repository\PanierRepository;
use App\Repository\ProduitRepository;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class CompteController extends AbstractController
{
//    #[Route('/compte', name: 'app_compte')]
//    public function index(ProduitRepository $produit, CategorieRepository $categorie): Response
//    {
//        return $this->render('compte/index.html.twig', [
//            'produits' => $produit->findAll(),
//            'categories' => $categorie
//        ]);
//    }

    #[Route('/souhait', name: 'app_souhait')]
    public function souhait(ProduitRepository $produit, CategorieRepository $categorie): Response
    {
        return $this->render('compte/souhait.html.twig', [
            'produits' => $produit->findAll(),
            'categories' => $categorie
        ]);
    }

    #[Route('/panier', name: 'app_panier')]
    public function panier(ManagerRegistry $doctrine, PanierRepository $panier, ProduitRepository $produit, CategorieRepository $categorie, ?Panier $paniers, Request $request): Response
    {

        return $this->render('compte/panier.html.twig', [
            'paniers' => $panier->findBy(array('user'=>$this->getUser())),
            'produits' => $produit->findAll(),
            'categories' => $categorie->findAll(),
            'panier' => $paniers,
        ]);

    }

    #[Route('/compte', name: 'app_compte')]
    public function gestion_compte(CategorieRepository $categorie, PanierRepository $paniers, AdresseRepository $adresse, CommandeRepository $commande): Response
    {
        return $this->render('compte/gestion_compte/compte.html.twig', [
            'categories' => $categorie->findAll(),
            'paniers' => $paniers->findBy(array('user'=>$this->getUser())),
            'adresse' => $adresse->findBy(array('user'=>$this->getUser())),
            'commandes' => $commande->findBy(array('user'=>$this->getUser())),
            'user' => $this->getUser(),
        ]);
    }

    #[Route('/gestion_compte/commande', name: 'app_gescompte_com')]
    public function gestion_compte_com(CategorieRepository $categorie, PanierRepository $paniers, CommandeRepository $commande): Response
    {
        return $this->render('compte/gestion_compte/commande.html.twig', [
            'categories' => $categorie->findAll(),
            'paniers' => $paniers->findBy(array('user'=>$this->getUser())),
            'commandes' => $commande->findBy(array('user'=>$this->getUser()), array('createdAt'=>'desc')),
        ]);
    }

    #[Route('/gestion_compte/adresse', name: 'app_gescompte_ad')]
    public function gestion_compte_ad(CategorieRepository $categorie, PanierRepository $paniers, AdresseRepository $adressse): Response
    {
        return $this->render('compte/gestion_compte/adresse.html.twig', [
            'categories' => $categorie->findAll(),
            'paniers' => $paniers->findBy(array('user'=>$this->getUser())),
            'adresse' => $adressse->findBy(array('user'=>$this->getUser())),
        ]);
    }
}

templates/compte/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello CompteController!{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="example-wrapper">
    <h1>Hello {{ controller_name }}! ✅</h1>

    This friendly message is coming from:
    <ul>
        <li>Your controller at <code><a href="{{ 'D:/Projet/ecommerce_version4/src/Controller/CompteController.php'|file_link(0) }}">src/Controller/CompteController.php</a></code></li>
        <li>Your template at <code><a href="{{ 'D:/Projet/ecommerce_version4/templates/compte/index.html.twig'|file_link(0) }}">templates/compte/index.html.twig</a></code></li>
    </ul>
</div>
{% endblock %}

templates/compte/panier.html.twig
{% extends 'base.html.twig' %}

{% block title %}panier{% endblock %}

{% block body %}
    <!-- ========== MAIN CONTENT ========== -->
    <main id="content" role="main" class="cart-page">
        <!-- breadcrumb -->
        <div class="bg-gray-13 bg-md-transparent">
            <div class="container">
                <!-- breadcrumb -->
                <div class="my-md-3">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-3 flex-nowrap flex-xl-wrap overflow-auto overflow-xl-visble">
                            <li class="breadcrumb-item flex-shrink-0 flex-xl-shrink-1"><a href="../home/index.html">Home</a></li>
                            <li class="breadcrumb-item flex-shrink-0 flex-xl-shrink-1 active" aria-current="page">Cart</li>
                        </ol>
                    </nav>
                </div>
                <!-- End breadcrumb -->
            </div>
        </div>
        <!-- End breadcrumb -->

        <div class="container">
            <div class="mb-4">
                <h1 class="text-center">Cart</h1>
            </div>
            <div class="mb-10 cart-table">
                <form class="mb-4" action="#" method="post" name="panier">
                    <table class="table" cellspacing="0">
                        <thead>
                        <tr>
                            <th class="product-remove">&nbsp;</th>
                            <th class="product-thumbnail">&nbsp;</th>
                            <th class="product-name">Product</th>
                            <th class="product-price">Price</th>
                            <th class="product-quantity w-lg-15">Quantity</th>
                            <th class="product-subtotal">Total</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for panier in paniers %}
                            <tr class="">
                                    <td class="text-center">
                                        <a href="{{ path("sup_panier", {'id': panier.id}) }}" class="text-gray-32 font-size-26">X</a>
                                    </td>
                                    <td class="d-none d-md-table-cell">
                                        <a href="{{ path("app_boutique_detail", {'id': panier.produit.id}) }}"><img class="img-fluid max-width-100 p-1 border border-color-1" src="{{ panier.produit.couvertureImg }}" alt="Image Description" width="300" height="300"></a>
                                    </td>

                                    <td data-title="Product">
                                        <a href="#" class="text-gray-90">{{ panier.produit.nom }}</a>
                                    </td>

                                    <td data-title="Price">
                                        <span class="">{{ panier.produit.prix/100 }}</span>
                                    </td>

                                    <td data-title="Quantity">
                                        <span class="sr-only">Quantity</span>
                                        <!-- Quantity -->
                                        <div class="border rounded-pill py-1 width-122 w-xl-80 px-3 border-color-1">
                                            <div class="js-quantity row align-items-center">
                                                <div class="col">
                                                    <input class="js-result form-control h-auto border-0 rounded p-0 shadow-none" type="text" value="1" name="quantite">
                                                </div>
                                                <div class="col-auto pr-1">
                                                    <a class="js-minus btn btn-icon btn-xs btn-outline-secondary rounded-circle border-0" href="javascript:;">
                                                        <small class="fas fa-minus btn-icon__inner"></small>
                                                    </a>
                                                    <a class="js-plus btn btn-icon btn-xs btn-outline-secondary rounded-circle border-0" href="javascript:;">
                                                        <small class="fas fa-plus btn-icon__inner"></small>
                                                    </a>
                                                </div>
                                            </div>
                                        </div>

                                        <!-- End Quantity -->
                                    </td>

                                    <td data-title="Total">
                                        {% set total = panier.prix * panier.quantite %}
                                        <span class="">{{ total/100 }}</span>
                                    </td>
                                </tr>
                        {% endfor %}
                        <tr>
                            <td colspan="6" class="border-top space-top-2 justify-content-center">
                                <div class="pt-md-3">
                                    <div class="d-block d-md-flex flex-center-between">
                                        <div class="d-md-flex">
                                            <button type="submit" class="btn btn-soft-secondary mb-3 mb-md-0 font-weight-normal px-5 px-md-4 px-lg-5 w-100 w-md-auto">Mise a jours</button>
                                            <a href="{{ path("app_commande") }}" class="btn btn-primary-dark-w ml-md-2 px-5 px-md-4 px-lg-5 w-100 w-md-auto d-none d-md-inline-block">Proceed to checkout</a>
                                        </div>
                                    </div>
                                </div>
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </form>
            </div>
            <div class="mb-8 cart-total">
                <div class="row">
                    <div class="col-xl-5 col-lg-6 offset-lg-6 offset-xl-7 col-md-8 offset-md-4">
                        <div class="border-bottom border-color-1 mb-3">
                            <h3 class="d-inline-block section-title mb-0 pb-2 font-size-26">Cart totals</h3>
                        </div>
                        <table class="table mb-3 mb-md-0">
                            <tbody>
                            <tr class="cart-subtotal">
                                <th>Subtotal</th>
                                {% set montant = 0 %}
                                {% for panier in paniers %}
                                    {% set montant = montant + (panier.prix * panier.quantite) %}
                                {% endfor %}
                                {% set montant = montant / 100 %}
                                <td data-title="Subtotal"><span class="amount">{{ montant }}</span></td>
                            </tr>
                            <tr class="shipping">
                                <th>Shipping</th>
                                <td data-title="Shipping">
                                    Flat Rate: <span class="amount">1500 fr</span>
                                </td>
                            </tr>
                            <tr class="order-total">
                                <th>Total</th>
                                {% set total_final = (montant) + 1500 %}
                                <td data-title="Total"><strong><span class="amount">{{ total_final }}</span></strong></td>
                            </tr>
                            </tbody>
                        </table>
                        <button type="button" class="btn btn-primary-dark-w ml-md-2 px-5 px-md-4 px-lg-5 w-100 w-md-auto d-md-none">Proceed to checkout</button>
                    </div>
                </div>
            </div>
        </div>
    </main>
    <!-- ========== END MAIN CONTENT ========== -->
{% endblock %}

templates/compte/souhait.html.twig
{% extends 'base.html.twig' %}

{% block title %}Hello ShopController!{% endblock %}

{% block body %}
    <!-- ========== MAIN CONTENT ========== -->
    <main id="content" role="main" class="cart-page">
        <!-- breadcrumb -->
        <div class="bg-gray-13 bg-md-transparent">
            <div class="container">
                <!-- breadcrumb -->
                <div class="my-md-3">
                    <nav aria-label="breadcrumb">
                        <ol class="breadcrumb mb-3 flex-nowrap flex-xl-wrap overflow-auto overflow-xl-visble">
                            <li class="breadcrumb-item flex-shrink-0 flex-xl-shrink-1"><a href="../home/index.html">Home</a></li>
                            <li class="breadcrumb-item flex-shrink-0 flex-xl-shrink-1 active" aria-current="page">Wishlist</li>
                        </ol>
                    </nav>
                </div>
                <!-- End breadcrumb -->
            </div>
        </div>
        <!-- End breadcrumb -->

        <div class="container">
            <div class="my-6">
                <h1 class="text-center">My wishlist on Electro</h1>
            </div>
            <div class="mb-16 wishlist-table">
                <form class="mb-4" action="#" method="post">
                    <div class="table-responsive">
                        <table class="table" cellspacing="0">
                            <thead>
                            <tr>
                                <th class="product-remove">&nbsp;</th>
                                <th class="product-thumbnail">&nbsp;</th>
                                <th class="product-name">Product</th>
                                <th class="product-price">Unit Price</th>
                                <th class="product-Stock w-lg-15">Stock Status</th>
                                <th class="product-subtotal min-width-200-md-lg">&nbsp;</th>
                            </tr>
                            </thead>
                            <tbody>
                            <tr>
                                <td class="text-center">
                                    <a href="#" class="text-gray-32 font-size-26">×</a>
                                </td>
                                <td class="d-none d-md-table-cell">
                                    <a href="#"><img class="img-fluid max-width-100 p-1 border border-color-1" src="../../assets/img/300X300/img6.jpg" alt="Image Description"></a>
                                </td>

                                <td data-title="Product">
                                    <a href="#" class="text-gray-90">Ultra Wireless S50 Headphones S50 with Bluetooth</a>
                                </td>

                                <td data-title="Unit Price">
                                    <span class="">$1,100.00</span>
                                </td>

                                <td data-title="Stock Status">
                                    <!-- Stock Status -->
                                    <span>In stock</span>
                                    <!-- End Stock Status -->
                                </td>

                                <td>
                                    <button type="button" class="btn btn-soft-secondary mb-3 mb-md-0 font-weight-normal px-5 px-md-4 px-lg-5 w-100 w-md-auto">Add to Cart</button>
                                </td>
                            </tr>
                            <tr class="">
                                <td class="text-center">
                                    <a href="#" class="text-gray-32 font-size-26">×</a>
                                </td>
                                <td class="d-none d-md-table-cell">
                                    <a href="#"><img class="img-fluid max-width-100 p-1 border border-color-1" src="../../assets/img/300X300/img7.png" alt="Image Description"></a>
                                </td>

                                <td data-title="Product">
                                    <a href="#" class="text-gray-90">Widescreen NX Mini F1 SMART NX</a>
                                </td>

                                <td data-title="Unit Price">
                                    <span class="">$685.00</span>
                                </td>

                                <td data-title="Stock Status">
                                    <!-- Stock Status -->
                                    <span>In stock</span>
                                    <!-- End Stock Status -->
                                </td>

                                <td>
                                    <button type="button" class="btn btn-soft-secondary mb-3 mb-md-0 font-weight-normal px-5 px-md-4 px-lg-5 w-100 w-md-auto">Add to Cart</button>
                                </td>
                            </tr>
                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
        </div>
    </main>
    <!-- ========== END MAIN CONTENT ========== -->
{% endblock %}